/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { PerspectiveCamera } from "@react-three/drei";

export default function ProfileDisc({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/9lchdTa7IfHrClrg/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#e9e9e9"]} />
      <group {...props} dispose={null}>
        <group name="Ring" position={[65.99, 82.92, 101.85]}>
          <mesh
            name="Boolean"
            geometry={nodes.Boolean.geometry}
            material={materials.Black}
            castShadow
            receiveShadow
            position={[0, 0, 0]}
          >
            <mesh
              name="Cutout"
              geometry={nodes.Cutout.geometry}
              material={materials.Black}
              visible={false}
              castShadow
              receiveShadow
              position={[0, 0, 0]}
              rotation={[0.67, -0.48, -0.53]}
              scale={1}
            />
            <mesh
              name="Ring1"
              geometry={nodes.Ring1.geometry}
              material={materials.Black}
              visible={false}
              castShadow
              receiveShadow
              position={[0, 0, 0]}
              rotation={[0.67, -0.48, -0.53]}
              scale={1}
            />
          </mesh>
        </group>
        <group name="Center Picture" position={[65.96, 82.89, 101.81]}>
          <mesh
            name="Back Face"
            geometry={nodes["Back Face"].geometry}
            material={materials[""]}
            castShadow
            receiveShadow
            position={[-5.64, -6.66, -8.84]}
            rotation={[-0.65, 0.47, -0.54]}
            scale={1}
          />
          <mesh
            name="Front Face"
            geometry={nodes["Front Face"].geometry}
            material={materials["Front Face Material"]}
            castShadow
            receiveShadow
            position={[5.44, 6.43, 8.53]}
            rotation={[-0.65, 0.47, -0.54]}
            scale={1}
          />
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials[""]}
            castShadow
            receiveShadow
            position={[0.02, 0.03, 0.04]}
            rotation={[0.67, -0.48, -0.53]}
          />
        </group>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1000}
          shadow-camera-right={1000}
          shadow-camera-top={1000}
          shadow-camera-bottom={-1000}
          position={[-431.35, 646.36, 334]}
        />
        <PerspectiveCamera
          name="1"
          makeDefault={true}
          far={100000}
          near={5}
          fov={45}
          position={[589.31, 679.64, 730.15]}
          rotation={[-0.76, 0.54, 0.46]}
          scale={1}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
        />
      </group>
    </>
  );
}
